# Generated by Django 4.2 on 2024-03-15 00:33

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, verbose_name='Name')),
                ('category_registerdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_category',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_dni', models.CharField(max_length=8)),
                ('client_genre', models.CharField(max_length=1)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_birthdate', models.DateField(null=True)),
                ('client_address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_client',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_registerdate', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=20, null=True)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_state', models.CharField(choices=[('0', 'Requested'), ('1', 'Payed')], default='0', max_length=1)),
                ('order_client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.client')),
            ],
            options={
                'db_table': 'tbl_order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, verbose_name='Name')),
                ('product_description', models.TextField(null=True, verbose_name='Description')),
                ('product_image', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('product_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('product_registerdate', models.DateTimeField(auto_now=True)),
                ('product_category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, related_name='Products', to='api.category', verbose_name='Category')),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdetail_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('orderdetail_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderdetail_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.order')),
                ('orderdetail_product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.product')),
            ],
            options={
                'db_table': 'tbl_orderdetail',
            },
        ),
    ]
