# Generated by Django 4.2 on 2024-03-15 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category_id',
            new_name='category_id',
        ),
    ]
