# Generated by Django 4.2 on 2024-03-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_product_category_id_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='orderdetail_order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='orderdetail_product',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='id',
        ),
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='orderdetail_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
